spring.application.name=GinumApps
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/ginum_apps}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}


spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
server.port=${SERVER_PORT:8081}



#jwt.secret=6YS6/n7egeA1Ezi5PpPWKTE7HQ9/4DKbfAKXjiJ1U6M=
jwt.secret = nDifHMj9c8hZfQEXQhuSUwTt6s7effZPjyM88Gt3Ea0=
jwt.expiration=3600000
#spring.main.allow-circular-references=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
# Security: Prevent large payload attacks (Buffer Overflow / DoS)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
